apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: port1
      port: 8086
      targetPort: 8086
    - name: port2
      port: 8087
      targetPort: 8087