apiVersion: v1
kind: Service
metadata:
  name: clanovi
spec:
  selector:
    app: clanovi
  ports:
    - name: port1
      port: 8080
      targetPort: 8080
    - name: port2
      port: 8081
      targetPort: 8081