apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
<<<<<<< HEAD
        image: ammvic/email
=======
        image: ammvic/3faza-email
>>>>>>> 50ef361 (Izmena K8s foldera)
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://+:8084;http://+:8085
        ports:
        - containerPort: 8084
        - containerPort: 8085