apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  selector:
    app: email
  ports:
    - name: port1
      port: 8084
      targetPort: 8084
    - name: port2
      port: 8085
      targetPort: 8085